create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  description text,
  width_mm numeric(10,2) not null default 148.50,
  height_mm numeric(10,2) not null default 105.00,
  font_family text not null default 'Arial',
  header_color text not null default '#100e75',
  background_color text not null default '#f0f0f0',
  font_color text not null default '#171717',
  header_font_color text not null default '#ffffff',
  header_text_left text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.flashcards (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  collection_id bigint not null references public.collections(id) on delete cascade,
  front text not null,
  back text not null,
  header_right text,
  is_info_card boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.materials (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  collection_id bigint not null references public.collections(id) on delete cascade,
  internal_name text not null,
  original_filename text not null,
  page_range_start integer not null check (page_range_start >= 1),
  page_range_end integer not null check (page_range_end >= page_range_start),
  page_count integer not null check (page_count >= 1),
  storage_path text not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists collections_user_id_idx on public.collections (user_id);
create index if not exists flashcards_user_id_idx on public.flashcards (user_id);
create index if not exists flashcards_collection_id_idx on public.flashcards (collection_id);
create index if not exists materials_user_id_idx on public.materials (user_id);
create index if not exists materials_collection_id_idx on public.materials (collection_id);

create or replace function public.ensure_owned_collection_reference()
returns trigger
language plpgsql
as $$
declare
  owner_id uuid;
begin
  select user_id into owner_id from public.collections where id = new.collection_id;

  if owner_id is null then
    raise exception 'Collection not found';
  end if;

  if owner_id <> new.user_id then
    raise exception 'Collection does not belong to authenticated user';
  end if;

  return new;
end;
$$;

drop trigger if exists flashcards_set_updated_at on public.flashcards;
create trigger flashcards_set_updated_at
before update on public.flashcards
for each row
execute function public.set_updated_at();

drop trigger if exists materials_set_updated_at on public.materials;
create trigger materials_set_updated_at
before update on public.materials
for each row
execute function public.set_updated_at();

drop trigger if exists collections_set_updated_at on public.collections;
create trigger collections_set_updated_at
before update on public.collections
for each row
execute function public.set_updated_at();

drop trigger if exists flashcards_ensure_owned_collection_reference on public.flashcards;
create trigger flashcards_ensure_owned_collection_reference
before insert or update on public.flashcards
for each row
execute function public.ensure_owned_collection_reference();

drop trigger if exists materials_ensure_owned_collection_reference on public.materials;
create trigger materials_ensure_owned_collection_reference
before insert or update on public.materials
for each row
execute function public.ensure_owned_collection_reference();

alter table public.collections enable row level security;
alter table public.flashcards enable row level security;
alter table public.materials enable row level security;

create policy "collections_select_own"
on public.collections
for select
using (auth.uid() = user_id);

create policy "collections_insert_own"
on public.collections
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "collections_update_own"
on public.collections
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "collections_delete_own"
on public.collections
for delete
to authenticated
using (auth.uid() = user_id);

create policy "flashcards_select_own"
on public.flashcards
for select
to authenticated
using (auth.uid() = user_id);

create policy "flashcards_insert_own"
on public.flashcards
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "flashcards_update_own"
on public.flashcards
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "flashcards_delete_own"
on public.flashcards
for delete
to authenticated
using (auth.uid() = user_id);

create policy "materials_select_own"
on public.materials
for select
to authenticated
using (auth.uid() = user_id);

create policy "materials_insert_own"
on public.materials
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "materials_update_own"
on public.materials
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "materials_delete_own"
on public.materials
for delete
to authenticated
using (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('materials', 'materials', false, 15728640, array['application/pdf'])
on conflict (id) do nothing;

create policy "materials_storage_select"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'materials'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "materials_storage_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'materials'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "materials_storage_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'materials'
  and (storage.foldername(name))[1] = auth.uid()::text
);
